### ISSUE TITLE
Compile failed

### ISSUE THREAD

**Issue by thomasvanta** [cr8tr/omnidome#1]
Hi!
I'm on OS X 10.10 and trying to compile from source, I got this error:

```
CMake Error at cmake-files/qt.cmake:35 (find_package):
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Core" with any
  of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PR-- Configuring incomplete, errors occurred!
See also "/Users/fanta/Code/omnidome/CMakeFiles/CMakeOutput.log".
EFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  cmake-files/qt.cmake:77 (find_qt5_component)
  CMakeLists.txt:42 (setup_qt)

```
I have came installed from brew and qt from the offline installer in the same directory as omnidome.
Any other dependency I could be missing?

**Comment by cr8tr** [comment]
Hi,
Apparently Qt is in the wrong folder.
I just pushed a new version nad implemented an algorithm for scanning different qt version and should use the most suitable one.
Moreover, you can set a manual Qt Folder by setting the QT_PATH variable in CMakeLists.txt in Line 70.
example:
SET(QT_PATH /your/directory/Qt )
Hope this helps.

Best
Micha

**Comment by thomasvanta** [comment]
I got compiling with the previous commit, the issue was I had installed Qt 5.5, not 5.4.
Great Software by the way, clean and nice UI, perfect workflow. Making some tests now. 
My issue is that I cannot find the ISFs anywhere, I saw some references to Lichtpiraten Blogspot, but couldn't find any download.

**Comment by cr8tr** [comment]
Just pushed the isf into to the src/plugins folder.
Would be cool if you test them ;)
Best
Micha
