### ISSUE TITLE
Building on OSX, Qt Framework was not found.  You might set QT_PATH manually.

### ISSUE THREAD

**Issue by DanielArnett** [cr8tr/omnidome#10]
I followed the README. Installed [Qt OSX 64 bit clang from here](http://download.qt.io/archive/qt/5.4/5.4.2/) to /Users/Dan/code/qt5.4.2/ but when I ran cmake: 

`cmake . -DQT_PATH=/Users/Dan/code/qt5.4.2/5.4/clang_64/` 

I received this error.

```
-- Found CMakeMacros environment in /Users/Dan/code/omnidome/cmake-files
-- Setup build directories.
-- Build mode is Debug
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Omnidome 1.0.0
-- Qt Path: /Users/Dan/code/qt5.4.2/5.4/clang_64/
CMake Error at CMakeLists.txt:35 (MESSAGE):
  Qt Framework was not found.  You might set QT_PATH manually.
```

Any ideas?

**Comment by WilstonOreo** [comment]
Just -DQT_PATH=/Users/Dan/code/qt5.4.2 should be alright, but I haven't tested Qt 5.4 a while ago, i recommend Qt 5.6.

**Comment by DanielArnett** [comment]
Ahh, okay. The readme said 5.4. I'll give it a try...

**Comment by DanielArnett** [comment]
Same problem, I'll install qt5.6 and give it another go.

**Comment by DanielArnett** [comment]
For clarification both qt5.4.2 and omnidome are subdirectories of my  `code` directory.

**Comment by WilstonOreo** [comment]
i meant
cmake . -DQT_PATH=/Users/Dan/code/qt5.4.2 
(without /5.4/clang_64) should be alright.

**Comment by DanielArnett** [comment]
Yes, I understood. I tried `cmake . -DQT_PATH=/Users/Dan/code/qt5.4.2` and received the same error

**Comment by WilstonOreo** [comment]
ok, thanks for reporting the issue, will update the README now ;)

**Comment by DanielArnett** [comment]
Excellent, installing the latest version of Qt an using the above command solved the issue.
