### ISSUE TITLE
Qt Creator IDE

### ISSUE THREAD

**Issue by DanielArnett** [cr8tr/omnidome#11]
What IDE is typically used with omnidome? When I open the CMakeLists.txt in Qt Creator nothing opens, just an empty project.

**Comment by WilstonOreo** [comment]
I use vim ;)
Can check the CMakeLists.txt in Qt Creator later, maybe there is an error.

**Comment by WilstonOreo** [comment]
Yo, also happens on my side, will fix.

**Comment by DanielArnett** [comment]
Okay, just making sure that I wasn't doing something wrong. If you don't get to it I'll see what I can do. Did you write the interface in vim too? You're a stronger man than most, lol.

**Comment by WilstonOreo** [comment]
Ok, i got it working now in Qt Creator in Default build mode. The thing, i just completely refactored the build system on Sunday its not completely finished, so I want to merge these changes cleanly to master first, but maybe i get it done this evening.
I used Qt Designer to make most of the forms, the rest i hacked in vim ;)

**Comment by DanielArnett** [comment]
Sweet, did you have to add source files in CMakeLists, or was it something else? I'm accustomed to Creator's debugger so that'll help.

**Comment by DanielArnett** [comment]
Qt Creator still not working for me on OSX as of commit [b872fe3c530e51c641bd1072015263d71000b790](https://github.com/cr8tr/omnidome/commit/b872fe3c530e51c641bd1072015263d71000b790).

This is all I'm seeing is an empty window without even the CMakeLists.txt, and I can't CMake, build, or Run.
![screen shot 2016-06-09 at 11 18 05 am](https://cloud.githubusercontent.com/assets/3029502/15935090/1b6a8af0-2e34-11e6-82e8-886cce16815e.png)

**Comment by WilstonOreo** [comment]
Hmm, only tested it on linux, it worked there. The cmake setup is a bit different on mac, will check it out tomorrow morning ;)

**Comment by WilstonOreo** [comment]
Hmm, strange, I can run cmake from within Qt Creator, shows no errors but doesnt generate a makefile :-\

**Comment by WilstonOreo** [comment]
May check out this plugin:
https://github.com/h4tr3d/cmakeprojectmanager2

**Comment by WilstonOreo** [comment]
<img width="1440" alt="screen shot 2016-06-14 at 12 41 07" src="https://cloud.githubusercontent.com/assets/1030022/16039994/5e03541c-322d-11e6-932c-f8c4fc62eb2f.png">
After deleting CMakeCache.txt, the CMakeFiles folder and Omnidome.cbp, CMake worked for me

**Comment by DanielArnett** [comment]
Between your advice and [this StackOverflow](http://stackoverflow.com/questions/37737066/qt-creator-wont-open-cmake-c-project-in-osx) Q&A I got Qt Creator working with CMake on OSX.

```

down vote
unaccept
Open your Preferences (Cmd+, on Mac) and go to the Build & Run and then CMake tab, do you see any CMake version listed there? For me, I have to add a manual entry because it doesn't automatically find my CMake. My manual entry is set to /Applications/CMake.app/Contents/bin/cmake so compare that with what you have in your settings. Build & Run -> CMake tab showing the CMake path manually set to /Applications/CMake.app/Contents/bin/cmake Then restart Qt Creator and reopen your project. Go to Build & Run again and make sure the Kit you have selected for your project has a CMake Tool set (should be automatic if you have just the one CMake entry listed on the CMake tab). 
```
