### ISSUE TITLE
Low Framerate

### ISSUE THREAD

**Issue by DanielArnett** [cr8tr/omnidome#21]
What troubleshooting should a user perform when experiencing low output framerate? Assuming that we've already checked the input framerate of Omnidome, what's next? What can we do?

For my particular instance I am running a 2013 Mac Pro (trashcan mac). I am using 5 projectors via 2 TripleHead2Gos and one input directly from the Mac.

All projectors are currently at 1080p and I haven't tried lowering resolution yet. Omnidome is only using 60% CPU utilization.

**Comment by DanielArnett** [comment]
I dropped my projectors resolutions down from 1080p to 720p and don't see a noticeable difference in framerate.

**Comment by DanielArnett** [comment]
Solution: Minimize the preview windows on the right side of omnidome to hide the preview for each projector. This takes some significant CPU time away from rendering the output. My output has gone from ~15 fps to ~30 fps (guessing here).

**Comment by WilstonOreo** [comment]
Thanks for testing. Would be cool to have some real benchmarks on this, using the QBENCHMARK functionality :)
