### ISSUE TITLE
TripleHead2Go

### ISSUE THREAD

**Issue by DanielArnett** [cr8tr/omnidome#9]
Many in the VJ and fulldome community use TripleHead2Gos to offload some of the graphics processing for multiple projectors. Does omnidome currently work with TripleHead2Gos? What has been the experience for using 6+ projectors on a single Mac Pro?

**Comment by WilstonOreo** [comment]
Hi,
thanks for using omnidome. yes, omnidome has built in triple head support. Just connect your triple head and it will be detected as a screen with 3 subscreen in the screen setup menu. We used omnidome with 6 projectors on a hackintosh, no performance issues, especially in live mode.

Best
Micha

**Comment by DanielArnett** [comment]
Wow, excellent! Thanks Micha. I'll try it out tonight.
